```{r}
library(tidyr)
library(dplyr)
library(ggplot2)
library(ncdf4)
library(chron)
library(lattice)
library(RColorBrewer)
library(zoo)
library(animation)
library(berryFunctions)
library(patchwork)
ncin<-nc_open("cru_ts4.09.1901.2024.tmp.dat.nc")
ncin_p<-nc_open("cru_ts4.09.1901.2024.pre.dat.nc")


```

```{r}
time <- ncvar_get(ncin,"time")
tunits <- ncatt_get(ncin,"time","units")
tustr <- strsplit(tunits$value, " ")
tdstr <- strsplit(unlist(tustr)[3], "-")
tmonth <- as.integer(unlist(tdstr)[2])
tday <- as.integer(unlist(tdstr)[3])
tyear <- as.integer(unlist(tdstr)[1])
time_ch<-chron(time,origin=c(tmonth, tday, tyear))
time_m_y<-as.yearmon(time_ch)
Sys.setlocale("LC_TIME", "C")
time_m_y<-as.yearmon(time_ch)
time_id<-which(time_m_y=="Dec 1996")
time <-time_m_y[1:time_id] #czas do klimatu
tail(time)
```


```{r}
#NOWE
lon <- ncvar_get(ncin,"lon")
lat <- ncvar_get(ncin,"lat")

lon_id<-which(lon==14.75)
lat_id<-which(lat==57.75)
pinus1_tmp<-ncvar_get(ncin,"tmp",start=c(lon_id,lat_id,1),count=c(1,1,time_id))
pinus1_pre<-ncvar_get(ncin_p,"pre",start=c(lon_id,lat_id,1),count=c(1,1,time_id))

lon_id<-which(lon==18.75)
lat_id<-which(lat==64.75)
pinus2_tmp<-ncvar_get(ncin,"tmp",start=c(lon_id,lat_id,1),count=c(1,1,time_id))
pinus2_pre<-ncvar_get(ncin_p,"pre",start=c(lon_id,lat_id,1),count=c(1,1,time_id))

lon_id<-which(lon==21.75)
lat_id<-which(lat==67.75)
pinus3_tmp<-ncvar_get(ncin,"tmp",start=c(lon_id,lat_id,1),count=c(1,1,time_id))
pinus3_pre<-ncvar_get(ncin_p,"pre",start=c(lon_id,lat_id,1),count=c(1,1,time_id))
```

```{r}
make_1901_1996_df <- function(vec) {
  mat <- matrix(vec, ncol = 12, byrow = TRUE)
  df <- data.frame(rok=1901:1996, mat)
  colnames(df) <- c("rok", "I", "II", "III", "IV", "V", "VI",
      "VII", "VIII", "IX", "X", "XI", "XII")
  df <- round(df, digits=1)
  
  return(df)
}

list_tmp_1901_1996_df <- lapply(list(pinus1_tmp, pinus2_tmp, pinus3_tmp), make_1901_1996_df)
#teraz np.pinus1_tmp_df to lista_tmp_df[[1]]

list_pre_1901_1996_df <- lapply(list(pinus1_pre, pinus2_pre, pinus3_pre), make_1901_1996_df)

View(list_tmp_1901_1996_df[[1]])
```


```{r}
make_30_years_df <- function(dataframe, start_year) {
  df <- colMeans(dataframe[dataframe$rok >= start_year & dataframe$rok <= (start_year+29), -1], na.rm = TRUE)
  return(df)
}
list_tmp_1901_1930 <- lapply(list_tmp_1901_1996_df,make_30_years_df,start_year=1901)
list_tmp_1967_1996 <- lapply(list_tmp_1901_1996_df,make_30_years_df,start_year=1967)
list_pre_1901_1930 <- lapply(list_pre_1901_1996_df,make_30_years_df,start_year=1901)
list_pre_1967_1996 <- lapply(list_pre_1901_1996_df,make_30_years_df,start_year=1967)
```

```{r}
miesiace <- names(list_pre_1901_1930[[1]])

make_climate_30_years_df <- function(df_tmp, df_pre) {
  df <- data.frame(
    miesiac = factor(miesiace, levels = miesiace),
    temperatura = as.numeric(round(df_tmp, digits=1)),
    opady = as.numeric(round(df_pre, digits=1)))
    
  return(df)
}

list_climate_1901_1930_df <- mapply(make_climate_30_years_df, list_tmp_1901_1930, list_pre_1901_1930,SIMPLIFY = FALSE)
list_climate_1967_1996_df <- mapply(make_climate_30_years_df, list_tmp_1967_1996, list_pre_1967_1996, SIMPLIFY = FALSE)

View(list_climate_1901_1930_df[[1]])

```

```{r}
plot_climate <- function(df, title) {
  climateGraph(
  temp = df$temperatura,
  rain = df$opady,
  labs = levels(df$miesiac),
  main = title,
  coltemp = "red",
  colrain = "blue"
)
}

titles_1901_1930 <- c(
  "Okres 1901–1930 - pinus1",
  "Okres 1901–1930 – pinus2",
  "Okres 1901–1930 – pinus3"
)

titles_1967_1996 <- c(
  "Okres 1967-1996 - pinus1",
  "Okres 1967-1996 – pinus2",
  "Okres 1967-1996 – pinus3"
)

mapply(plot_climate,list_climate_1901_1930_df, titles_1901_1930 )
mapply(plot_climate,list_climate_1967_1996_df, titles_1967_1996 )
  
```

```{r}
make_2periods_climate_df <- function(df1901,df1967) {
  df <- data.frame(
    miesiąc = factor(miesiace, levels = miesiace),
    tmp1901_1930 = df1901$temperatura,
    tmp1967_1996 = df1967$temperatura,
    opady1901_1930 = df1901$opady,
    opady1967_1996 = df1967$opady
  )
  return(df)
}

list_2periods_climate_df <- mapply(make_2periods_climate_df, list_climate_1901_1930_df, list_climate_1967_1996_df, SIMPLIFY=FALSE)
```

```{r}
plot_climate_2periods <- function(df) {
  p1 <- ggplot(df, aes(x = `miesiąc`, group = 1)) +
  geom_line(aes(y = tmp1901_1930, color = "1901–1930"), size = 1.1) +
  geom_point(aes(y = tmp1901_1930, color = "1901–1930"), size = 2) +
  geom_line(aes(y = tmp1967_1996, color = "1967–1996"), size = 1.1) +
  geom_point(aes(y = tmp1967_1996, color = "1967–1996"), size = 2) +
  labs(y = "Temperatura [°C]", x = "Miesiąc", color = "Okres") +
  scale_color_manual(values = c("1901–1930" = "orange", "1967–1996" = "darkred")) +
  theme_minimal()
  
  p2 <- ggplot(df, aes(x = `miesiąc`)) +
  geom_col(aes(y = opady1901_1930, fill = "1901–1930"),
  position = position_nudge(x = -0.2), width = 0.4) +
  geom_col(aes(y = opady1967_1996, fill = "1967–1996"),
  position = position_nudge(x = 0.2), width = 0.4) +
  scale_fill_manual(values = c("1901–1930" = "skyblue", "1967–1996" = "blue")) +
  labs(y = "Opady [mm]", x = "Miesiąc", fill = "Okres") +
  theme_minimal()
  
  klimatogram <- p1 / p2 + plot_layout(heights = c(1, 1))
  klimatogram
}

lapply(list_2periods_climate_df, plot_climate_2periods)
```

```{r}
# ZMIANA ŚREDNIEJ ROCZNEJ TEMP I OPADÓW

mean_yearly <- function(dataframe) {
  df <- data.frame(
    rok = 1901:1996,
    sr_temp = rowMeans(dataframe[,-1],na.rm=TRUE)
  )
  return(df)
}

list_mean_yearly_temp <- lapply(list_tmp_1901_1996_df, mean_yearly)
list_mean_yearly_pre <- lapply(list_pre_1901_1996_df, mean_yearly)
#View(list_mean_yearly_temp[[3]])

for (n in 1:3) {
  plot <- ggplot(list_mean_yearly_temp[[n]], aes(rok, sr_temp)) + geom_line(color='red') + geom_smooth(method="lm", color='red') + labs( x='Rok', y="Średnia temperatura [°C]")
  print(plot)
}
for (n in 1:3) {
  plot <- ggplot(list_mean_yearly_pre[[n]], aes(rok, sr_temp)) + geom_line(color='blue') + geom_smooth(method="lm", color='blue') + labs( x='Rok', y="Średnie roczne opady [mm]")
  print(plot)
}




```
```{r}
## czy trend linowy jest istotny statycztycznie?

for (n in 1:3) {
  print(paste("Temperatura: Pinus",n, "trend liniowy"))
  lm <- lm(list_mean_yearly_temp[[n]]$sr_temp~list_mean_yearly_temp[[n]]$rok)
  print(summary(lm))
}

for (n in 1:3) {
  print(paste("Opady: Pinus",n, "trend liniowy"))
  lm <- lm(list_mean_yearly_pre[[n]]$sr_temp~list_mean_yearly_pre[[n]]$rok)
  print(summary(lm))
}

```


```{r}
library(dplR)

class(swed314r.crn.noaa) <- c("crn", "data.frame")
colnames(swed314r.crn.noaa)<-c("res","samp.depth")

class(swed317r.crn.noaa) <- c("crn", "data.frame")
colnames(swed317r.crn.noaa)<-c("res","samp.depth")

class(swed319r.crn.noaa) <- c("crn", "data.frame")
colnames(swed319r.crn.noaa)<-c("res","samp.depth")




plot(swed314r.crn.noaa)
plot(swed317r.crn.noaa)
plot(swed319r.crn.noaa)
plot(swed314r.crn.noaa, add.spline = TRUE, nyrs = 20)
plot(swed317r.crn.noaa, add.spline = TRUE, nyrs = 20)
plot(swed319r.crn.noaa, add.spline = TRUE, nyrs = 20)

```

```{r}
#Dane klimatyczne dla lokalizacji chronologii
tmp_matrix_pinus1 <- matrix(pinus1_tmp, ncol = 12, byrow = TRUE)
tmp_matrix_pinus2 <- matrix(pinus2_tmp, ncol = 12, byrow = TRUE)
tmp_matrix_pinus3 <- matrix(pinus3_tmp, ncol = 12, byrow = TRUE)


tmp_pinus1_df <- data.frame(rok=1901:1996, tmp_matrix_pinus1)
tmp_pinus2_df <- data.frame(rok=1901:1996, tmp_matrix_pinus2)
tmp_pinus3_df <- data.frame(rok=1901:1996, tmp_matrix_pinus3)

lapply(
        list(tmp_pinus1_df,tmp_pinus2_df,tmp_pinus3_df), 
       \(df){ #funkcja anonimowa
            colnames(df) <- c("rok", "I", "II", "III", "IV", "V", "VI","VII", "VIII", "IX", "X", "XI", "XII") 
            df<-round(df, digits=1)
            View(df)
            boxplot(df[,2:13], border="blue", col="orange", main="Rozkład temperatur", xlab="miesiące", ylab="tmp [st.C]")
        }
      )
```


```{r}
#install.packages("treeclim")
#install.packages("lubridate")
library(treeclim)
library(dplyr)
library(lubridate)

year<-year(time_m_y[1:time_id])
month<-rep(seq(1,12),length(unique(year)))
clim_tmp_pinus1<-data.frame(year,month,pinus1_tmp)
tail(clim_tmp_pinus1)

pinus1_chron<-select(swed314r.crn.noaa,-samp.depth)
head(pinus1_chron)

#korelacja stacjonarna
pinus1_stat<-dcc(pinus1_chron, clim_tmp_pinus1, selection = -5:9, method = "correlation")
plot(pinus1_stat)

#korelacja ruchoma
pinus1_moving<-dcc(pinus1_chron, clim_tmp_pinus1, selection = -5:9, method = "correlation", dynamic = "moving", win_size = 34, timespan=c(1901,1996))
plot(pinus1_moving)
```
```{r}
#install.packages("segmented")
library(segmented)
mapply(
       \(tmp_df,title)
        {
          df <- data.frame(rok = tmp_df$rok,tmp = tmp_df$X12)
          df<-slice(df, 1:98)
          
          fit_lm <- lm(tmp ~ rok, data = df)
         
          fit_segmented1 <- segmented(fit_lm, seg.Z = ~rok, npsi = 1) 
          summary(fit_segmented1)
          plot(fit_segmented1, ylim=c(-25,5), main= paste("tmp grudzień",title, sep=" - "))
          lines(df$rok, df$tmp)
          lines.segmented(fit_segmented1)
          points.segmented(fit_segmented1)
        },list(tmp_pinus1_df,tmp_pinus2_df,tmp_pinus3_df),list("pinus 1","pinus 2","pinus 3")
       )
```

